"""empty message

Revision ID: 442aa2781ef4
Revises: a904aa5e22e7
Create Date: 2024-03-26 01:20:42.939462

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '442aa2781ef4'
down_revision = 'a904aa5e22e7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('order',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('association_table_order',
    sa.Column('order', sa.Integer(), nullable=True),
    sa.Column('drink', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['drink'], ['drink.id'], ),
    sa.ForeignKeyConstraint(['order'], ['order.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('association_table_order')
    op.drop_table('order')
    # ### end Alembic commands ###
